//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESSS
    {
        public long AdressID { get; set; }
        public long OrgDoc_ID { get; set; }
        public int AdressType_ID { get; set; }
        public string AdressDetails { get; set; }
        public int Tehsil_ID { get; set; }
        public int EnterByUser_ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyByDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> IsActiveDate { get; set; }
    
        public virtual ORGDOC ORGDOC { get; set; }
        public virtual TEHSIL TEHSIL { get; set; }
    }
}
