//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT
    {
        public DISTRICT()
        {
            this.TEHSILs = new HashSet<TEHSIL>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
    
        public virtual ICollection<TEHSIL> TEHSILs { get; set; }
    }
}
