//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public DOCUMENT()
        {
            this.ORGDOCs = new HashSet<ORGDOC>();
        }
    
        public int DocumentID { get; set; }
        public string DocumentName { get; set; }
        public bool IsActive { get; set; }
        public int EnteredByUser_ID { get; set; }
        public System.DateTime EntryTime { get; set; }
        public Nullable<int> UpdateByUser_ID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual ICollection<ORGDOC> ORGDOCs { get; set; }
    }
}
