//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        public ORGANIZATION()
        {
            this.ORGDOCs = new HashSet<ORGDOC>();
            this.BUSINESSTYPEs = new HashSet<BUSINESSTYPE>();
        }
    
        public long OrganizationID { get; set; }
        public string OrgRegNo { get; set; }
        public string DurationofFirm { get; set; }
        public System.DateTime FormADate { get; set; }
        public string FormGNo { get; set; }
        public System.DateTime FirmStartDate { get; set; }
        public int OrgType_ID { get; set; }
        public string NotaryPublicName { get; set; }
        public string NotaryPublicLicenseNo { get; set; }
        public System.DateTime DeedAgreementDate { get; set; }
        public int EnterByUser_ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> IsActiveDate { get; set; }
        public System.DateTime FormASubmissionDate { get; set; }
        public string FormAPath { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> ApprovedByUser_ID { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Objectives { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public Nullable<System.DateTime> LicenseIssueDate { get; set; }
    
        public virtual ORGTYPE ORGTYPE { get; set; }
        public virtual ICollection<ORGDOC> ORGDOCs { get; set; }
        public virtual ICollection<BUSINESSTYPE> BUSINESSTYPEs { get; set; }
    }
}
