//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGFEE
    {
        public long TransactionID { get; set; }
        public int FeeType_ID { get; set; }
        public long Org_ID { get; set; }
        public decimal FeeAmount { get; set; }
        public string ChallanNo { get; set; }
        public System.DateTime FeeDate { get; set; }
        public Nullable<int> BankDistrict_ID { get; set; }
        public int EnteredByUser_ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Bank_ID { get; set; }
    }
}
