//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTNERNAMEnADD
    {
        public long PAdressID { get; set; }
        public long Partner_ID { get; set; }
        public string PartnerName { get; set; }
        public string PartnerAdress { get; set; }
        public long OrgDoc_ID { get; set; }
        public int EnterByUser_ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> IsActiveDate { get; set; }
    }
}
