//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENREPORT
    {
        public long RReportID { get; set; }
        public int RReportYear { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public long Org_ID { get; set; }
        public Nullable<System.DateTime> RRResolutionDate { get; set; }
        public bool IsAuthorityLetter { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EnterByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
    }
}
