//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    
    public partial class usp_GetOrgRenewalReports_Result1
    {
        public long RReportID { get; set; }
        public int RReportYear { get; set; }
        public long OrganizationID { get; set; }
        public string FileNo { get; set; }
        public bool IsAuthorityLetter { get; set; }
        public Nullable<System.DateTime> RRResolutionDate { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
