//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WITNESS
    {
        public long WitnessID { get; set; }
        public string WitnessName { get; set; }
        public string WitnessCNIC { get; set; }
        public string WitnessONIC { get; set; }
        public string WitnessAddress { get; set; }
        public string WitnessContactNo { get; set; }
        public string WitnessMobileNo { get; set; }
        public long OrgDoc_ID { get; set; }
        public string WitnessPassportNo { get; set; }
        public string WitnessCitizenNo { get; set; }
        public int EnterByUser_ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> IsActiveDate { get; set; }
    
        public virtual ORGDOC ORGDOC { get; set; }
    }
}
